#!/usr/bin/env python3
"""
Interactive setup wizard for the Podcast Pipeline.
Walks you through every step — no assumptions.
Run: python3 setup.py
"""

import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

BASE_DIR = Path(__file__).parent
ENV_FILE = BASE_DIR / ".env"
STATE_FILE = BASE_DIR / "storage_state.json"


# ── Helpers ──────────────────────────────────────────────────────────────────

def clear():
    os.system("cls" if os.name == "nt" else "clear")


def banner(title):
    clear()
    print("=" * 60)
    print(f"  {title}")
    print("=" * 60)
    print()


def ask(question, required=True, default=""):
    """Ask a single question. Keep asking until they answer if required."""
    while True:
        if default:
            answer = input(f"  {question} [{default}]: ").strip()
            if not answer:
                return default
        else:
            answer = input(f"  {question}: ").strip()
        if answer or not required:
            return answer
        print("  ^ This one's required. Try again.\n")


def ask_yes_no(question, default=None):
    """Ask a yes/no question."""
    suffix = " (y/n)"
    if default is True:
        suffix = " (Y/n)"
    elif default is False:
        suffix = " (y/N)"

    while True:
        answer = input(f"  {question}{suffix}: ").strip().lower()
        if not answer and default is not None:
            return default
        if answer in ("y", "yes"):
            return True
        if answer in ("n", "no"):
            return False
        print("  ^ Type 'y' or 'n'.\n")


def ask_choice(question, options):
    """Ask them to pick from a numbered list. Returns the option dict."""
    print(f"  {question}\n")
    for i, opt in enumerate(options, 1):
        print(f"    {i}. {opt['label']}")
    print()

    while True:
        answer = input("  Enter number: ").strip()
        try:
            idx = int(answer)
            if 1 <= idx <= len(options):
                return options[idx - 1]
        except ValueError:
            pass
        print(f"  ^ Pick a number between 1 and {len(options)}.\n")


def ask_multi_choice(question, options):
    """Ask them to pick one or more from a numbered list. Returns list of option dicts."""
    print(f"  {question}\n")
    for i, opt in enumerate(options, 1):
        print(f"    {i}. {opt['label']}")
    print()
    print("  You can pick more than one. Example: 1,3")
    print()

    while True:
        answer = input("  Enter number(s): ").strip()
        try:
            picks = [int(x.strip()) for x in answer.split(",")]
            if all(1 <= p <= len(options) for p in picks):
                return [options[p - 1] for p in picks]
        except ValueError:
            pass
        print(f"  ^ Enter numbers between 1 and {len(options)}, separated by commas.\n")


def run_cmd(cmd, check=True):
    """Run a shell command and return output."""
    result = subprocess.run(cmd, shell=True, capture_output=True, text=True)
    if check and result.returncode != 0:
        return None
    return result.stdout.strip()


def save_env(config):
    """Write the .env file from config dict."""
    lines = ["# Generated by setup.py — do NOT commit this file\n"]
    for key, value in config.items():
        lines.append(f"{key}={value}")
    ENV_FILE.write_text("\n".join(lines) + "\n")


# ── Setup Steps ──────────────────────────────────────────────────────────────

def step_welcome():
    banner("Podcast Pipeline Setup")
    print("  This will walk you through setting up your own automated")
    print("  podcast pipeline. It takes about 10 minutes.")
    print()
    print("  What it does:")
    print("    1. Takes your content (website, YouTube, topics, etc.)")
    print("    2. Turns each piece into a podcast episode (via NotebookLM)")
    print("    3. Writes SEO metadata (via Claude AI)")
    print("    4. Uploads to your podcast host (Transistor.fm)")
    print("    5. Optionally writes a blog post for each episode")
    print()
    print("  You'll need a few accounts (free trials are fine to start):")
    print("    - Google account (for NotebookLM)")
    print("    - Transistor.fm account ($19/month — hosts your podcast)")
    print("    - Anthropic account (for Claude AI — ~$0.03/day)")
    print()
    input("  Press Enter to start...")


def step_podcast_info():
    banner("Step 1: Your Podcast")
    print("  Let's start with the basics about your podcast.\n")

    name = ask("What do you want to call your podcast?")
    niche = ask("What's it about? (e.g., 'real estate investing', 'dog training', 'cooking')")

    print(f"\n  Got it: \"{name}\" — a podcast about {niche}.")
    print()

    print("  Who's your target audience? This helps the AI write content")
    print("  that speaks directly to them.\n")
    market = ask("Describe your audience (e.g., 'small business owners in the US', 'Indian real estate agents')", required=False)

    config = {"PODCAST_NAME": name, "PODCAST_NICHE": niche}
    if market:
        config["TARGET_MARKET"] = market

    print()
    print("  Are there any Reddit communities where your audience hangs out?")
    print("  The pipeline searches Reddit for real discussions to make content better.\n")
    subreddits = ask("Subreddit names, comma-separated (e.g., 'realestateinvesting, landlords')", required=False)
    if subreddits:
        config["REDDIT_SUBREDDITS"] = subreddits

    print()
    print("  Any specific facts the pipeline should always check?")
    print("  For example: 'Use INR not USD', 'Our product starts at $49/mo',")
    print("  'WhatsApp not SMS for this market'\n")
    rules = ask("Fact-check rules (or press Enter to skip)", required=False)
    if rules:
        config["FACT_CHECK_RULES"] = rules

    print()
    input("  Press Enter to continue...")

    return config


def step_content_source():
    banner("Step 2: Where Does Your Content Come From?")
    print("  The pipeline needs source material to turn into podcast episodes.")
    print("  This could be articles on your website, YouTube videos, an RSS feed,")
    print("  or you can just type in topics and it'll research them.\n")

    sources = ask_multi_choice(
        "Where should it pull content from?",
        [
            {"label": "My website — it'll scrape articles/pages", "value": "website"},
            {"label": "My YouTube channel — it'll use video transcripts", "value": "youtube"},
            {"label": "An RSS feed — blog or news feed", "value": "rss"},
            {"label": "I'll provide topics — it'll research and write from scratch", "value": "manual"},
        ],
    )

    config = {}
    source_types = [s["value"] for s in sources]
    config["CONTENT_SOURCE_TYPES"] = ",".join(source_types)

    if "website" in source_types:
        print()
        url = ask("What's your website URL? (e.g., https://example.com)")
        config["WEBSITE_URL"] = url

        print()
        print("  How should it find content on your site?\n")
        crawl = ask_choice(
            "Pick one:",
            [
                {"label": "Scrape the whole site (finds all pages/articles automatically)", "value": "full"},
                {"label": "Just one section (e.g., /blog or /help)", "value": "section"},
                {"label": "I'll give it a sitemap URL", "value": "sitemap"},
            ],
        )
        config["WEBSITE_CRAWL_MODE"] = crawl["value"]

        if crawl["value"] == "section":
            print()
            section = ask("What section? (e.g., /blog, /articles, /help)")
            config["WEBSITE_SECTION"] = section
        elif crawl["value"] == "sitemap":
            print()
            sitemap = ask("What's the sitemap URL? (e.g., https://example.com/sitemap.xml)")
            config["WEBSITE_SITEMAP_URL"] = sitemap

    if "youtube" in source_types:
        print()
        yt_url = ask("What's your YouTube channel URL?")
        config["YOUTUBE_CHANNEL_URL"] = yt_url

    if "rss" in source_types:
        print()
        rss_url = ask("What's the RSS feed URL?")
        config["RSS_FEED_URL"] = rss_url

    if "manual" in source_types:
        print()
        print("  No problem — you can add topics later in data/topics.json")
        print("  or pass them on the command line: python3 run.py --topic \"Your topic here\"")

    print()
    print(f"  Content sources configured: {', '.join(source_types)}")
    print()
    input("  Press Enter to continue...")

    return config


def step_notebooklm():
    banner("Step 3: NotebookLM Setup")
    print("  NotebookLM is what generates the podcast audio.")
    print("  It's made by Google and sounds like two people having")
    print("  a real conversation about your content.\n")
    print("  You need a Google account. The free tier gives you")
    print("  3 episodes per day. The Plus plan ($20/mo) gives you 20/day.\n")

    has_account = ask_yes_no("Do you have a Google account?", default=True)

    if not has_account:
        print()
        print("  You'll need one. Go to https://accounts.google.com and sign up.")
        print("  Come back and run setup.py again when you're ready.")
        print()
        input("  Press Enter to exit...")
        sys.exit(0)

    print()
    print("  Now we need to log you into NotebookLM so the pipeline")
    print("  can generate audio automatically.\n")
    print("  A browser window will open. Log in with your Google account")
    print("  and then come back here.\n")

    ready = ask_yes_no("Ready to open the browser?", default=True)

    if ready:
        try:
            result = subprocess.run(
                [sys.executable, "-m", "notebooklm", "login"],
                cwd=str(BASE_DIR),
                timeout=120,
            )
            if result.returncode == 0:
                print("\n  NotebookLM authentication saved.\n")
            else:
                print("\n  Something went wrong. You can try again later by running:")
                print("    python3 -m notebooklm login\n")
        except FileNotFoundError:
            print("\n  notebooklm package not installed yet. We'll install it in a moment.")
            print("  After setup, run: python3 -m notebooklm login\n")
        except subprocess.TimeoutExpired:
            print("\n  Timed out. You can try again later by running:")
            print("    python3 -m notebooklm login\n")
    else:
        print()
        print("  No problem. Run this later before your first episode:")
        print("    python3 -m notebooklm login")

    print()
    plan = ask_choice(
        "What NotebookLM plan are you on?",
        [
            {"label": "Free (3 episodes/day)", "value": "free"},
            {"label": "Plus — $20/mo (20 episodes/day)", "value": "plus"},
            {"label": "Not sure", "value": "free"},
        ],
    )

    episodes_per_day = 3 if plan["value"] == "free" else 20

    print(f"\n  Set to {episodes_per_day} episodes per day.\n")
    input("  Press Enter to continue...")

    return {"EPISODES_PER_DAY": str(episodes_per_day)}


def step_transistor():
    banner("Step 4: Podcast Hosting (Transistor.fm)")
    print("  Transistor.fm hosts your podcast and distributes it to")
    print("  Spotify, Apple Podcasts, Amazon Music, etc.\n")
    print("  It's $19/month and supports unlimited episodes.\n")

    has_account = ask_yes_no("Do you have a Transistor.fm account?")

    if not has_account:
        print()
        print("  Sign up at: https://transistor.fm")
        print()
        print("  Once you have an account, you'll need two things:")
        print("    1. Your API key (Settings → API → copy the key)")
        print("    2. Create a show (the name of your podcast)")
        print()
        setup_later = ask_yes_no("Want to skip this for now and set it up later?", default=True)
        if setup_later:
            print("\n  No problem. Add TRANSISTOR_API_KEY and TRANSISTOR_SHOW_ID to your .env later.\n")
            input("  Press Enter to continue...")
            return {}

    print()
    print("  To find your API key:")
    print("    1. Log into transistor.fm")
    print("    2. Go to Account → API (left sidebar)")
    print("    3. Copy the API key\n")

    api_key = ask("Paste your Transistor API key", required=False)

    config = {}
    if api_key:
        config["TRANSISTOR_API_KEY"] = api_key

        print()
        print("  Now we need your show ID. If you haven't created a show yet,")
        print("  go to transistor.fm and create one first.\n")
        print("  To find the show ID:")
        print("    1. Go to your show's dashboard on transistor.fm")
        print("    2. Look at the URL — it'll be something like:")
        print("       transistor.fm/shows/12345")
        print("    3. That number is your show ID\n")

        show_id = ask("What's your show ID?", required=False)
        if show_id:
            config["TRANSISTOR_SHOW_ID"] = show_id

    print()
    input("  Press Enter to continue...")
    return config


def step_claude():
    banner("Step 5: Claude AI (SEO & Blog Writing)")
    print("  Claude writes SEO titles, descriptions, and tags for each episode.")
    print("  If you want blog posts, it writes those too.\n")
    print("  Cost: about $0.03/day (very cheap).\n")
    print("  You need an Anthropic API key:\n")
    print("    1. Go to: https://console.anthropic.com")
    print("    2. Sign up or log in")
    print("    3. Go to API Keys → Create Key")
    print("    4. Copy the key (starts with sk-ant-)\n")

    api_key = ask("Paste your Anthropic API key", required=False)

    config = {}
    if api_key:
        config["ANTHROPIC_API_KEY"] = api_key
    else:
        print("\n  No problem. Add ANTHROPIC_API_KEY to your .env later.")

    print()
    input("  Press Enter to continue...")
    return config


def step_gemini():
    banner("Step 6: Google Gemini (Transcription)")
    print("  Gemini transcribes your podcast audio into text.")
    print("  This helps with SEO and lets listeners read along.\n")
    print("  Cost: about $0.05/day.\n")

    want_transcription = ask_yes_no("Do you want automatic transcription?", default=True)

    config = {}
    if want_transcription:
        print()
        print("  To get a Gemini API key:\n")
        print("    1. Go to: https://aistudio.google.com/apikey")
        print("    2. Click 'Create API Key'")
        print("    3. Copy the key (starts with AIza)\n")

        api_key = ask("Paste your Gemini API key", required=False)
        if api_key:
            config["GOOGLE_AI_API_KEY"] = api_key
        else:
            print("\n  Add GOOGLE_AI_API_KEY to your .env later.")
    else:
        print("\n  Skipping transcription. You can enable it later.\n")

    config["ENABLE_TRANSCRIPTION"] = "true" if want_transcription else "false"

    input("  Press Enter to continue...")
    return config


def step_blog():
    banner("Step 7: Blog Site (Optional)")
    print("  The pipeline can also generate a blog post for each episode")
    print("  and publish it to a website automatically.\n")
    print("  The blog is free to host (Cloudflare Pages) and helps with SEO.\n")

    want_blog = ask_yes_no("Do you want a blog site for your episodes?")

    config = {"ENABLE_BLOG": "true" if want_blog else "false"}

    if want_blog:
        print()
        has_domain = ask_yes_no("Do you have a domain name for it?")

        if has_domain:
            domain = ask("What's the domain? (e.g., mypodcast.com)")
            config["SITE_URL"] = f"https://{domain.replace('https://', '').replace('http://', '')}"
        else:
            print()
            print("  No problem. You can get one later (~$10/year from Namecheap, Google Domains, etc.).")
            print("  The blog will still work on a free Cloudflare URL in the meantime.")
            config["SITE_URL"] = ""

        print()
        site_name = ask("What should the blog be called?", required=False)
        if site_name:
            config["SITE_NAME"] = site_name

        print()
        tagline = ask("One-line tagline for the site (shows in search results)", required=False)
        if tagline:
            config["SITE_TAGLINE"] = tagline

        print()
        has_affiliate = ask_yes_no("Do you have an affiliate link or CTA link to include in posts?", default=False)
        if has_affiliate:
            link = ask("Paste the full URL")
            config["AFFILIATE_LINK"] = link

        print()
        print("  Blog setup complete. After setup finishes, check DEPLOY.md")
        print("  for instructions on connecting your domain to Cloudflare Pages.\n")

    input("  Press Enter to continue...")
    return config


def step_email():
    banner("Step 8: Daily Email Summary (Optional)")
    print("  The pipeline can email you a daily summary of what it did:")
    print("  how many episodes published, any errors, etc.\n")

    want_email = ask_yes_no("Do you want daily email summaries?", default=False)

    config = {"ENABLE_EMAIL": "true" if want_email else "false"}

    if want_email:
        print()
        email = ask("What email should summaries go to?")
        config["GMAIL_ADDRESS"] = email

        print()
        print("  To send emails, the pipeline needs a Gmail App Password.")
        print("  This is NOT your regular Gmail password. Here's how to get one:\n")
        print("    1. Go to: https://myaccount.google.com/apppasswords")
        print("    2. You may need to enable 2-factor auth first")
        print("    3. Create a new app password for 'Mail'")
        print("    4. Copy the 16-character password\n")

        app_pass = ask("Paste your Gmail App Password (or skip for later)", required=False)
        if app_pass:
            config["GMAIL_APP_PASSWORD"] = app_pass
        else:
            print("\n  Add GMAIL_APP_PASSWORD to your .env later.")

    print()
    input("  Press Enter to continue...")
    return config


def step_schedule():
    banner("Step 9: How Often Should It Run?")
    print("  The pipeline can run automatically on a schedule,")
    print("  or you can run it manually whenever you want.\n")

    mode = ask_choice(
        "How do you want to run it?",
        [
            {"label": "Automatically — runs every day on its own", "value": "auto"},
            {"label": "Manually — I'll run it when I want", "value": "manual"},
            {"label": "Not sure yet — I'll decide later", "value": "manual"},
        ],
    )

    config = {"RUN_MODE": mode["value"]}

    if mode["value"] == "auto":
        print()
        print("  How often should it cycle? The default is every 25 hours,")
        print("  which gives NotebookLM's daily limit time to reset.\n")
        hours = ask("How many hours between cycles?", default="25")
        config["CYCLE_HOURS"] = hours

    print()
    input("  Press Enter to continue...")
    return config


def step_install_deps():
    banner("Step 10: Installing Dependencies")
    print("  Setting up Python virtual environment and installing packages...\n")

    venv_dir = BASE_DIR / "venv"

    if not venv_dir.exists():
        print("  Creating virtual environment...")
        subprocess.run([sys.executable, "-m", "venv", str(venv_dir)], check=True)
        print("  Done.\n")

    pip = venv_dir / "bin" / "pip"
    if os.name == "nt":
        pip = venv_dir / "Scripts" / "pip"

    req_file = BASE_DIR / "requirements.txt"
    if req_file.exists():
        print("  Installing packages (this may take a minute)...\n")
        subprocess.run([str(pip), "install", "-r", str(req_file)], check=True)
        print("\n  All packages installed.\n")
    else:
        print("  No requirements.txt found — skipping.\n")

    input("  Press Enter to continue...")
    return {}


def step_summary(config):
    banner("Setup Complete!")
    print("  Here's what we configured:\n")

    print(f"    Podcast:        {config.get('PODCAST_NAME', '(not set)')}")
    print(f"    Niche:          {config.get('PODCAST_NICHE', '(not set)')}")

    sources = config.get("CONTENT_SOURCE_TYPES", "")
    print(f"    Content from:   {sources}")

    if config.get("WEBSITE_URL"):
        print(f"    Website:        {config['WEBSITE_URL']}")
    if config.get("YOUTUBE_CHANNEL_URL"):
        print(f"    YouTube:        {config['YOUTUBE_CHANNEL_URL']}")
    if config.get("RSS_FEED_URL"):
        print(f"    RSS:            {config['RSS_FEED_URL']}")

    eps = config.get("EPISODES_PER_DAY", "3")
    print(f"    Episodes/day:   {eps}")

    transistor = "configured" if config.get("TRANSISTOR_API_KEY") else "not yet"
    print(f"    Transistor:     {transistor}")

    claude = "configured" if config.get("ANTHROPIC_API_KEY") else "not yet"
    print(f"    Claude AI:      {claude}")

    blog = "yes" if config.get("ENABLE_BLOG") == "true" else "no"
    print(f"    Blog site:      {blog}")

    email = "yes" if config.get("ENABLE_EMAIL") == "true" else "no"
    print(f"    Daily emails:   {email}")

    run_mode = config.get("RUN_MODE", "manual")
    print(f"    Run mode:       {run_mode}")

    print()
    print("  Your config is saved to .env")
    print()
    print("  ─────────────────────────────────────")
    print("  NEXT STEPS:")
    print("  ─────────────────────────────────────")
    print()

    if not config.get("TRANSISTOR_API_KEY"):
        print("  1. Sign up at https://transistor.fm and add your")
        print("     API key + show ID to .env\n")

    if not config.get("ANTHROPIC_API_KEY"):
        print("  2. Get a Claude API key at https://console.anthropic.com")
        print("     and add it to .env\n")

    print("  Then run your first episode:")
    print()
    print("    python3 run.py")
    print()
    print("  Or run a full batch:")
    print()
    print("    python3 run.py --batch")
    print()

    if run_mode == "auto":
        print("  To start the automatic scheduler:")
        print()
        print("    python3 scheduler.py")
        print()

    if blog == "yes":
        print("  For blog setup instructions, see DEPLOY.md")
        print()


# ── Main ─────────────────────────────────────────────────────────────────────

def main():
    config = {}

    step_welcome()

    # Run each step, merge results into config
    steps = [
        step_podcast_info,
        step_content_source,
        step_notebooklm,
        step_transistor,
        step_claude,
        step_gemini,
        step_blog,
        step_email,
        step_schedule,
        step_install_deps,
    ]

    for step in steps:
        result = step()
        config.update(result)

    # Save .env
    save_env(config)

    # Show summary
    step_summary(config)


if __name__ == "__main__":
    main()
